# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# GitHub Pages Deployment - Currently Disabled
# Manual deployment is active via GitHub Pages settings

name: Deploy to GitHub Pages (Disabled)

# Trigger: Manual deployment only
on:
  workflow_dispatch: # Manual trigger only

jobs:
  info:
    runs-on: ubuntu-latest
    if: false # Disabled - manual deployment is active
    steps:
      - name: Deployment Info
        run: |
          echo "This workflow is disabled"
          echo "Manual deployment via GitHub Pages is currently active"
          echo "Repository: nightingale-cms"
          echo "Branch: main"
          echo "URL: https://skigim.github.io/nightingale-cms/"
