name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./App
          publish_branch: gh-pages
          force_orphan: true

# Set permissions for the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write
